name: build

on: push

jobs:
  build:
    strategy:
      matrix:
        arch: [x86]
        config: [debug, release]

    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Re
        uses: osdeverr/actions-setup-re@v3
        with:
          re-version: latest
      
      - name: Set up VsDevCmd
        uses: egor-tensin/vs-shell@v2
        with:
          arch: ${{ matrix.arch }}
    
      - name: Build the project
        run: re --arch ${{ matrix.arch }} --configuration ${{ matrix.config }}
      
      - name: Create CI artifact
        uses: actions/upload-artifact@v3
        with:
          name: wcecl-${{ github.ref_name }}-${{ matrix.arch }}-${{ matrix.config }}-${{ github.run_id }}
          path: ./out/${{ matrix.arch }}-windows-${{ matrix.config }}/build